// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { EffectStructures$Type } from "./EffectStructures";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EffectStructures"]: EffectStructures$Type;
    ["src/effects/EffectStructures.sol:EffectStructures"]: EffectStructures$Type;
  }

  interface ContractTypesMap {
    ["EffectStructures"]: GetContractReturnType<EffectStructures$Type["abi"]>;
    ["src/effects/EffectStructures.sol:EffectStructures"]: GetContractReturnType<EffectStructures$Type["abi"]>;
  }
}
