// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface EffectStructures$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "EffectStructures",
  "sourceName": "src/effects/EffectStructures.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "string",
          "name": "_message",
          "type": "string"
        }
      ],
      "name": "RulesEngineEvent",
      "type": "event"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "EffectStructures",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EffectStructures$Type["abi"]>>;
  export function deployContract(
    contractName: "src/effects/EffectStructures.sol:EffectStructures",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EffectStructures$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "EffectStructures",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EffectStructures$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "src/effects/EffectStructures.sol:EffectStructures",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EffectStructures$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "EffectStructures",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EffectStructures$Type["abi"]>>;
  export function getContractAt(
    contractName: "src/effects/EffectStructures.sol:EffectStructures",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EffectStructures$Type["abi"]>>;
}
