// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { RulesStorageStructure$Type } from "./RulesStorageStructure";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RulesStorageStructure"]: RulesStorageStructure$Type;
    ["src/RulesStorageStructure.sol:RulesStorageStructure"]: RulesStorageStructure$Type;
  }

  interface ContractTypesMap {
    ["RulesStorageStructure"]: GetContractReturnType<RulesStorageStructure$Type["abi"]>;
    ["src/RulesStorageStructure.sol:RulesStorageStructure"]: GetContractReturnType<RulesStorageStructure$Type["abi"]>;
  }
}
