// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ExampleUserContract$Type } from "./ExampleUserContract";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ExampleUserContract"]: ExampleUserContract$Type;
    ["src/ExampleUserContract.sol:ExampleUserContract"]: ExampleUserContract$Type;
  }

  interface ContractTypesMap {
    ["ExampleUserContract"]: GetContractReturnType<ExampleUserContract$Type["abi"]>;
    ["src/ExampleUserContract.sol:ExampleUserContract"]: GetContractReturnType<ExampleUserContract$Type["abi"]>;
  }
}
