// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IRulesEngine$Type } from "./IRulesEngine";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IRulesEngine"]: IRulesEngine$Type;
    ["src/IRulesEngine.sol:IRulesEngine"]: IRulesEngine$Type;
  }

  interface ContractTypesMap {
    ["IRulesEngine"]: GetContractReturnType<IRulesEngine$Type["abi"]>;
    ["src/IRulesEngine.sol:IRulesEngine"]: GetContractReturnType<IRulesEngine$Type["abi"]>;
  }
}
