// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IRulesEngine$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IRulesEngine",
  "sourceName": "src/IRulesEngine.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "contractAddress",
          "type": "address"
        },
        {
          "internalType": "bytes",
          "name": "functionSignature",
          "type": "bytes"
        },
        {
          "internalType": "bytes",
          "name": "arguments",
          "type": "bytes"
        }
      ],
      "name": "checkPolicies",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IRulesEngine",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IRulesEngine$Type["abi"]>>;
  export function deployContract(
    contractName: "src/IRulesEngine.sol:IRulesEngine",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IRulesEngine$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IRulesEngine",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IRulesEngine$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "src/IRulesEngine.sol:IRulesEngine",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IRulesEngine$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IRulesEngine",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IRulesEngine$Type["abi"]>>;
  export function getContractAt(
    contractName: "src/IRulesEngine.sol:IRulesEngine",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IRulesEngine$Type["abi"]>>;
}
