// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { FCEncodingLib$Type } from "./FCEncodingLib";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["FCEncodingLib"]: FCEncodingLib$Type;
    ["src/utils/FCEncodingLib.sol:FCEncodingLib"]: FCEncodingLib$Type;
  }

  interface ContractTypesMap {
    ["FCEncodingLib"]: GetContractReturnType<FCEncodingLib$Type["abi"]>;
    ["src/utils/FCEncodingLib.sol:FCEncodingLib"]: GetContractReturnType<FCEncodingLib$Type["abi"]>;
  }
}
