// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface FCEncodingLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "FCEncodingLib",
  "sourceName": "src/utils/FCEncodingLib.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220ef0d3effba491cbf605b8cec9e2c73c96d6d56c9b01bcb79cd9bd9806da3884164736f6c634300081b0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220ef0d3effba491cbf605b8cec9e2c73c96d6d56c9b01bcb79cd9bd9806da3884164736f6c634300081b0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "FCEncodingLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<FCEncodingLib$Type["abi"]>>;
  export function deployContract(
    contractName: "src/utils/FCEncodingLib.sol:FCEncodingLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<FCEncodingLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "FCEncodingLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<FCEncodingLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "src/utils/FCEncodingLib.sol:FCEncodingLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<FCEncodingLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "FCEncodingLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<FCEncodingLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "src/utils/FCEncodingLib.sol:FCEncodingLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<FCEncodingLib$Type["abi"]>>;
}
