// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { RuleEncodingLibrary$Type } from "./RuleEncodingLibrary";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RuleEncodingLibrary"]: RuleEncodingLibrary$Type;
    ["src/RuleEncodingLibrary.sol:RuleEncodingLibrary"]: RuleEncodingLibrary$Type;
  }

  interface ContractTypesMap {
    ["RuleEncodingLibrary"]: GetContractReturnType<RuleEncodingLibrary$Type["abi"]>;
    ["src/RuleEncodingLibrary.sol:RuleEncodingLibrary"]: GetContractReturnType<RuleEncodingLibrary$Type["abi"]>;
  }
}
