/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "EffectStructures",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EffectStructures__factory>;
    getContractFactory(
      name: "ExampleUserContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExampleUserContract__factory>;
    getContractFactory(
      name: "IRulesEngine",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRulesEngine__factory>;
    getContractFactory(
      name: "RuleEncodingLibrary",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RuleEncodingLibrary__factory>;
    getContractFactory(
      name: "RulesEngineRunLogic",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RulesEngineRunLogic__factory>;

    getContractAt(
      name: "EffectStructures",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EffectStructures>;
    getContractAt(
      name: "ExampleUserContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ExampleUserContract>;
    getContractAt(
      name: "IRulesEngine",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRulesEngine>;
    getContractAt(
      name: "RuleEncodingLibrary",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RuleEncodingLibrary>;
    getContractAt(
      name: "RulesEngineRunLogic",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RulesEngineRunLogic>;

    deployContract(
      name: "EffectStructures",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EffectStructures>;
    deployContract(
      name: "ExampleUserContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ExampleUserContract>;
    deployContract(
      name: "IRulesEngine",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRulesEngine>;
    deployContract(
      name: "RuleEncodingLibrary",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RuleEncodingLibrary>;
    deployContract(
      name: "RulesEngineRunLogic",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RulesEngineRunLogic>;

    deployContract(
      name: "EffectStructures",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EffectStructures>;
    deployContract(
      name: "ExampleUserContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ExampleUserContract>;
    deployContract(
      name: "IRulesEngine",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRulesEngine>;
    deployContract(
      name: "RuleEncodingLibrary",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RuleEncodingLibrary>;
    deployContract(
      name: "RulesEngineRunLogic",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RulesEngineRunLogic>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
