/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace RulesStorageStructure {
  export type ArgumentsStruct = {
    argumentTypes: BigNumberish[];
    values: BytesLike[];
  };

  export type ArgumentsStructOutput = [
    argumentTypes: bigint[],
    values: string[]
  ] & { argumentTypes: bigint[]; values: string[] };
}

export interface RuleEncodingLibraryInterface extends Interface {
  getFunction(nameOrSignature: "customEncoder"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "customEncoder",
    values: [RulesStorageStructure.ArgumentsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "customEncoder",
    data: BytesLike
  ): Result;
}

export interface RuleEncodingLibrary extends BaseContract {
  connect(runner?: ContractRunner | null): RuleEncodingLibrary;
  waitForDeployment(): Promise<this>;

  interface: RuleEncodingLibraryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  customEncoder: TypedContractMethod<
    [arguments: RulesStorageStructure.ArgumentsStruct],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "customEncoder"
  ): TypedContractMethod<
    [arguments: RulesStorageStructure.ArgumentsStruct],
    [string],
    "view"
  >;

  filters: {};
}
