// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { RulesEngineRunLogic$Type } from "./RulesEngineRunLogic";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RulesEngineRunLogic"]: RulesEngineRunLogic$Type;
    ["src/RulesEngineRunLogic.sol:RulesEngineRunLogic"]: RulesEngineRunLogic$Type;
  }

  interface ContractTypesMap {
    ["RulesEngineRunLogic"]: GetContractReturnType<RulesEngineRunLogic$Type["abi"]>;
    ["src/RulesEngineRunLogic.sol:RulesEngineRunLogic"]: GetContractReturnType<RulesEngineRunLogic$Type["abi"]>;
  }
}
