/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  EffectStructures,
  EffectStructuresInterface,
} from "../../effects/EffectStructures";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "_message",
        type: "string",
      },
    ],
    name: "RulesEngineEvent",
    type: "event",
  },
] as const;

export class EffectStructures__factory {
  static readonly abi = _abi;
  static createInterface(): EffectStructuresInterface {
    return new Interface(_abi) as EffectStructuresInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): EffectStructures {
    return new Contract(address, _abi, runner) as unknown as EffectStructures;
  }
}
